### PR TITLE
Added translate alias t

### PR DESCRIPTION
**Pull request by fmvilas**
#### :tophat: What? Why?

Adding alias `t` to `translate` function.
#### :pushpin: Related tasks?

https://redbooth.com/a/#!/projects/1205355/tasks/19374450

### CODE REVIEW

**Comment by mllocs** [comment]
:+1:

**Comment by sauloperez** [comment]
please, add some pressure to this PR https://github.com/attilahorvath/i18n-globals/pull/2. If merged we won't need our fork.

:+1:

**Comment by sauloperez** [comment]
LOL after my complain it got merged https://github.com/attilahorvath/i18n-globals/pull/2

I think there's no need for this then

**Comment by fmvilas** [comment]
:clap: :clap: However let's continue with this fork since this guy seems to not be interested in maintaining the gem.

**Pull request merged**
